Add support for using different transports via .config file. Add ansible as a transport option in addition to pssh and ssh.

diff --git a/cfssh/cfssh b/cfssh/cfssh
--- a/cfssh/cfssh
+++ b/cfssh/cfssh
@@ -141,7 +141,7 @@ function clean_tmp_files {
 }
 
 function clean_pssh_out {
-  if [ "$USE_PSSH" == 'true' ]
+  if [ "$TRANSPORT" == 'pssh' ]
   then
     rm -rf $PSSH_OUTDIR
   fi
@@ -151,7 +151,10 @@ GREP="zgrep -e"
 L='L'
 
 SAVEOUT=false
-SERIAL=false
+
+. $DIR/.config
+#TRANSPORT=$(awk -F= '$1=="TRANSPORT" {print $2}' $DIR/.config)
+#PARALLELISM=$(awk -F= '$1=="PARALLELISM" {print $2}' $DIR/.config)
 
 while getopts ac:g:hilqo:s OPT
 do
@@ -165,26 +168,27 @@ do
     o) SAVEOUT=true
        TMPFILE=$OPTARG
       ;;
-    s) SERIAL=true ;;
+    s) PARALLELISM=1 ;;
     *) usage ;;
   esac
 done
 
 shift $((OPTIND-1))
 
-
-if [ "$SERIAL" != 'true' ]
+if [[ -z "$TRANSPORT" || -z "$PARALLELISM" ]]
 then
-  which pssh > /dev/null 2>&1
-  if [ $? -eq 0 ]
-  then
-    USE_PSSH=true
-  else
-    USE_PSSH=false
-  fi
+  echo "TRANSPORT and/or PARALLELISM not specified, see $DIR/.config."
+  exit 1
 fi
 
-if [ "$USE_PSSH" == 'true' ]
+which $TRANSPORT > /dev/null 2>&1
+if [ $? -ne 0 ]
+then
+  echo "TRANSPORT=$TRANSPORT and $TRANSPORT is not found."
+  exit 1
+fi
+
+if [ "$TRANSPORT" == 'pssh' ]
 then
   PSSH_OUTDIR="/tmp/.$NAME.pssh.$$"
   if [ -e "$PSSH_OUTDIR" ]
@@ -354,7 +358,7 @@ then
   usage
 fi
 
-if [[ "$QUIET" != 'true' && "$USE_PSSH" != 'true' || $NAME == 'cfgrep-request' ]]
+if [[ "$QUIET" != 'true' && "$TRANSPORT" != 'pssh' && "$TRANSPORT" != 'ansible' || $NAME == 'cfgrep-request' ]]
 then
   echo
 fi
@@ -437,7 +441,7 @@ ARGS=$(echo $ARGS | sed 's/*/\\*/g')
 if [[ $NAME != 'cftail' && $NAME != 'cftail-request' ]]
 then
 
-  if [ "$USE_PSSH" != 'true' ]
+  if [ "$TRANSPORT" == 'ssh' ]
   then
   
     for i in $SERVERS
@@ -453,7 +457,8 @@ then
       echo
     done
 
-  else
+  elif [ "$TRANSPORT" == 'pssh' ]
+  then
 
     HOSTS=""
     for i in $SERVERS
@@ -462,20 +467,42 @@ then
     done
 
     case $NAME in
-        "cfssh") pssh -i $HOSTS $ARGS ;;
-        "cfscp") pscp.pssh $HOSTS $1 $2 ;;
-        "cfcollect") pslurp $HOSTS -L $2 $1 . ;;
-        "cfgrep") pssh -i $HOSTS -o $PSSH_OUTDIR "$GREP \"$PATTERN\" $LOG | $TAIL | perl -pe 's/^\/.*?://'" ;;
-        "cfgrep-collate"|"cfgrep-request") pssh $HOSTS -o $PSSH_OUTDIR "$GREP \"$PATTERN\" $LOG | perl -pe 's/^\/.*?://' | sed -e \"s/^/[\$(hostname -s)] /\"" ;;
+      "cfssh") pssh -i $HOSTS $ARGS ;;
+      "cfscp") pscp.pssh $HOSTS $1 $2 ;;
+      "cfcollect") pslurp $HOSTS -L $2 $1 . ;;
+      "cfgrep") pssh -i $HOSTS -o $PSSH_OUTDIR "$GREP \"$PATTERN\" $LOG | $TAIL | perl -pe 's/^\/.*?://'" ;;
+      "cfgrep-collate"|"cfgrep-request") pssh $HOSTS -o $PSSH_OUTDIR "$GREP \"$PATTERN\" $LOG | perl -pe 's/^\/.*?://' | sed -e \"s/^/[\$(hostname -s)] /\"" ;;
     esac
+
+  elif [ "$TRANSPORT" == 'ansible' ]
+  then
+
+    HOSTS=$(echo $SERVERS | sed -e 's/ /,/g')
+
+    case $NAME in
+      "cfssh") ansible all -i $HOSTS -f $PARALLELISM -m shell -a "$ARGS" ;;
+      "cfscp") ansible all -i $HOSTS -f $PARALLELISM -m copy -a "src=$1 dest=$2" ;;
+      "cfcollect") ansible all -i $HOSTS -f $PARALLELISM -m fetch -a "src=$1 dest=$2/$(basename $1)-{{ inventory_hostname }} flat=yes" ;;
+      "cfgrep") ansible all -i $HOSTS -f $PARALLELISM -m shell -a "$GREP \"$PATTERN\" $LOG | $TAIL | perl -pe 's/^\/.*?://'" ;;
+      "cfgrep-collate"|"cfgrep-request") ansible all -i $HOSTS -f $PARALLELISM -m shell -a "$GREP \"$PATTERN\" $LOG | perl -pe 's/^\/.*?://' | sed -e \"s/^/[\$(hostname -s)] /\"" | tee $TMPFILE ;;
+    esac
+
+  else
+    echo "$TRANSPORT must be one of ssh, pssh, or ansible."
+    exit 1
   fi
 
   if [[ $NAME == 'cfgrep-collate' || $NAME == 'cfgrep-request' ]]
   then
     echo "*** collating results ***"
-    if [ "$USE_PSSH" == 'true' ]
+    if [ "$TRANSPORT" == 'pssh' ]
     then
       cat $PSSH_OUTDIR/* > $TMPFILE
+    fi
+    if [ "$TRANSPORT" == 'ansible' ]
+    then
+      awk '!/.* \| .* \| rc=.* >>/ {print}' $TMPFILE > $TMPFILE.ansible
+      mv $TMPFILE.ansible $TMPFILE
     fi
     sort -k 4 $TMPFILE > $TMPFILE.sort
     mv $TMPFILE.sort $TMPFILE
