Switch count to -c. Clean usage. Add -a option to show archived files.

diff --git a/cfssh/cfssh b/cfssh/cfssh
--- a/cfssh/cfssh
+++ b/cfssh/cfssh
@@ -24,26 +24,31 @@ function usage_common {
   if [ $# -ne 0 ]
   then
     echo "DETAILS:"
-    echo
     for i in "$@"
     do
-      echo "$i"
+      if [ -n "$i" ]
+      then
+        echo "$i"
+      fi
     done
     echo
   fi
 }
 
 function usage_case {
+  echo
   echo "  -i is optional to ignore case with grep"
 }
 
 function usage_log_file {
+  echo
   echo "  log_file is optional and defaults to automation.log"
   echo "    For CloudForms logs, log_file can be in the format of evm or evm.log"
   echo "    For any other files, use /the/full/path/to/file"
 }
 
 function usage_pattern {
+  echo
   echo "  pattern may be specified as a regex suitable for egrep taking care to prevent the shell from interpretation"
   if [[ $NAME != 'cfgrep-request' || $NAME != 'cftail-request' ]]
   then
@@ -52,20 +57,29 @@ function usage_pattern {
 }
 
 function usage_commas {
+  echo
   echo "  commas in request_id will automatically be stripped"
 }
 
 function usage_tail {
+  echo
   echo "  -l can be used to place output in separate window panes, by default output is merged"
+  echo
   echo "  In multitail:"
   echo "    Move around the buffer similar to less by pressing 'b'"
   echo "    Exit whatever context you are in by pressing 'q'"
 }
 
+function usage_grep {
+  echo
+  echo "  -a can be used to also grep archived logs"
+}
+
 function usage_output {
   if [[ $NAME == 'cfgrep-collate' || $NAME == 'cfgrep-request' ]]
   then
-    echo " -o outputfile can be used to save output to outputfile"
+    echo
+    echo "  -o outputfile can be used to save output to outputfile"
   fi
 }
 
@@ -74,7 +88,7 @@ function usage_help {
   echo
 }
 
-function usage_grep {
+function usage_regex {
   USAGE=$1
   DESCRIPTION=$2
   shift 2
@@ -93,12 +107,12 @@ function usage {
   echo
   case $NAME in
     "cfssh") usage_common "[-g group] command args" "ssh and run command with args" ;;
-    "cfscp") usage_common "[-g group] local_file remote_dest_dir" "push files out using scp" "  Only one file is supported at a time" ;;
-    "cfcollect") usage_common "[-g group] remote_file local_dest_dir" "pull files in using scp" "  Wildcards are accepted for remote_file but should only match one file" "  local_files are appended with remote hostname" ;;
-    "cfgrep") usage_grep "[-i] [-g group] pattern [log_file] [count]" "grep log_file for pattern and show last count number of lines" "  count is optional and used with tail to limit the output, default is $TAIL_NUMBER" "  If count is to be specified, log_file must also be specified" "  To show all lines specify count as 'all'";;
-    "cfgrep-collate") usage_grep "[-i] [-o outputfile] [-g group] pattern [log_file]" "grep log_file for pattern and collate all results and display using less" ;;
-    "cfgrep-request") usage_request "[-o outputfile] [-g group] request_id [log_file]" "grep log_file for request_id and all its associated tasks and collate all results and display with less" ;;
-    "cftail") usage_grep "[-i] [-l] [-g group] pattern [log_file]" "multitail and optionally grep pattern" "$(eval usage_tail)" ;;
+    "cfscp") usage_common "[-g group] local_file remote_dest_dir" "push files out using scp" " " "  Only one file is supported at a time" ;;
+    "cfcollect") usage_common "[-g group] remote_file local_dest_dir" "pull files in using scp" " " "  Wildcards are accepted for remote_file but should only match one file" " " "  local_files are appended with remote hostname" ;;
+    "cfgrep") usage_regex "[-a] [-c count] [-i] [-g group] pattern [log_file]" "grep log_file for pattern and show last count number of lines" " " "  -c count is optional and used with tail to limit the output, default is $TAIL_NUMBER" "  To show all lines specify -c all" "$(eval usage_grep)" ;;
+    "cfgrep-collate") usage_regex "[-a] [-i] [-o outputfile] [-g group] pattern [log_file]" "grep log_file for pattern and collate all results and display using less" "$(eval usage_grep)" ;;
+    "cfgrep-request") usage_request "[-a] [-o outputfile] [-g group] request_id [log_file]" "grep log_file for request_id and all its associated tasks and collate all results and display with less" "$(eval usage_grep)" ;;
+    "cftail") usage_regex "[-i] [-l] [-g group] pattern [log_file]" "multitail and optionally grep pattern" "$(eval usage_tail)" ;;
     "cftail-request") usage_request "[-l] [-g group] request_id [log_file]" "multitail and grep request_id and all its associated tasks" "$(eval usage_tail)" ;;
   esac
   echo "AVAILABLE GROUPS (default is all):"
@@ -119,14 +133,16 @@ function clean_tmp_file {
   rm -f $TMPFILE
 }
 
-GREP="egrep"
+GREP="zgrep -e"
 L='L'
 
 SAVEOUT=false
 
-while getopts g:ilo: OPT
+while getopts ac:g:ilo: OPT
 do
   case $OPT in
+    a) GREP_ARCHIVED=true ;;
+    c) TAIL_NUMBER=$OPTARG ;;
     g) group=$OPTARG ;;
     i) GREP="$GREP -i" ;;
     l) L='l' ;;
@@ -190,15 +206,7 @@ then
   echo
   echo "Not enough arguments!"
   usage
-elif [ $NAME == "cfgrep" ]
-then
-  if [[ $# -lt 1 || $# -gt 3 ]]
-  then
-    echo
-    echo "Wrong number of arguments!"
-    usage
-  fi
-elif [[ $NAME == 'cfgrep-collate' || $NAME == "cfgrep-request" || $NAME == "cftail" || $NAME == "cftail-request" ]]
+elif [[ $NAME == 'cfgrep' || $NAME == 'cfgrep-collate' || $NAME == "cfgrep-request" || $NAME == "cftail" || $NAME == "cftail-request" ]]
 then
   if [[ $# -ne 1 && $# -ne 2 ]]
   then
@@ -263,7 +271,17 @@ if [ $? -ne 0 ]
 then
   echo
   echo "Unable to find ruby with /usr/bin/env ruby.  Please make sure ruby is installed."
-  usage
+  echo
+  exit 1
+fi
+
+/usr/bin/env perl -v > /dev/null 2>&1
+if [ $? -ne 0 ]
+then
+  echo
+  echo "Unable to find perl with /usr/bin/env perl.  Please make sure perl is installed."
+  echo
+  exit 1
 fi
 
 group_good=false
@@ -335,16 +353,18 @@ then
   then
     LOG="/var/www/miq/vmdb/log/$(echo $LOG | sed 's/\.log$//').log"
   fi
+  if [[ $NAME == 'cfgrep' || $NAME == 'cfgrep-collate' || $NAME == 'cfgrep-request' ]]
+  then
+    if [ "$GREP_ARCHIVED" == 'true' ]
+    then
+      LOG="$LOG-* $LOG"
+    fi
+  fi
   if [[ $NAME == 'cfgrep' ]]
   then
-    if [ -n "$3" ]
+    if [ "$TAIL_NUMBER" == 'all' ]
     then
-      if [ "$3" == 'all' ]
-      then
-        TAIL_NUMBER=$ALL_TAIL_NUMBER
-      else
-        TAIL_NUMBER=$3
-      fi
+      TAIL_NUMBER=$ALL_TAIL_NUMBER
     fi
     TAIL="tail -$TAIL_NUMBER"
   else
@@ -365,8 +385,8 @@ then
       "cfssh") ssh root@$i $ARGS ;;
       "cfscp") scp $1 root@$i:$2 ;;
       "cfcollect") scp root@$i:$1 $2/$(basename $1)-$i ;;
-      "cfgrep") ssh root@$i $GREP "$PATTERN" $LOG \| $TAIL ;;
-      "cfgrep-collate"|"cfgrep-request") ssh root@$i $GREP "$PATTERN" $LOG | sed -e "s/^/[$i] /" >> $TMPFILE ;;
+      "cfgrep") ssh root@$i $GREP "$PATTERN" "$LOG" \| $TAIL ;;
+      "cfgrep-collate"|"cfgrep-request") ssh root@$i $GREP "$PATTERN" "$LOG" | perl -pe 's/^\/.*?://' | sed -e "s/^/[$i] /" >> $TMPFILE ;;
     esac
     echo
   done
