Remove default miqhosts.
Add check in miqssh to inform user of need to see INSTALL.txt if miqhosts does not exist.
Add INSTALL.txt contents.

diff --git a/miqssh/miqssh b/miqssh/miqssh
--- a/miqssh/miqssh
+++ b/miqssh/miqssh
@@ -12,6 +12,14 @@ miqhosts_file="$DIR/miqhosts"
 USER="root"
 REQUEST=false
 
+if [ ! -f $miqhosts_file ]
+then
+  echo
+  echo "Some initial setup is required to use this.  See $DIR/INSTALL.txt."
+  echo
+  exit 1
+fi
+
 if [ $NAME == "miqgrep-collate" ]
 then
   NAME=miqgrep
